import { useState } from 'react';
import { Link, NavLink } from 'react-router-dom';
import Brand from './Brand';
import { useMemberSession } from '../features/account/Account';
const navigation = [['/jobs', 'Latest jobs'], ['/results', 'Results'], ['/admit-cards', 'Admit cards'], ['/tools', 'Tools & AI']];
export function Header() {
  const [menu, setMenu] = useState(false), session = useMemberSession();
  return <header className="portal-header saas-header"><div className="header-inner"><Link className="brand" to="/" aria-label="SarkariLinks home"><Brand /></Link><button className="menu-toggle secondary" aria-expanded={menu} aria-controls="navigation" onClick={() => setMenu(!menu)}>Menu</button><nav id="navigation" className={menu ? 'open' : ''} aria-label="Main navigation">{navigation.map(([path, label]) => <NavLink key={path} to={path} onClick={() => setMenu(false)}>{label}{path === '/tools' && <span className="nav-new">NEW</span>}</NavLink>)}<NavLink to="/tools/resume-builder" onClick={() => setMenu(false)}>Résumé builder</NavLink><Link className="mobile-account" to={session.data?.data ? '/account' : '/account/login'} onClick={() => setMenu(false)}>{session.data?.data ? 'My workspace' : 'Sign in / create account'}</Link></nav><Link className="button account-link" to={session.data?.data ? '/account' : '/account/login'}>{session.data?.data ? 'My workspace' : 'Get started'} <span aria-hidden="true">↗</span></Link></div></header>;
}
export function Footer() {
  return <footer className="portal-footer saas-footer"><div className="saas-footer-grid"><div><Link className="brand" to="/"><Brand /></Link><p>A clearer path to your next opportunity.<br />Jobs, useful tools and a workspace that fits you.</p><small>Independent information portal. Always verify eligibility, fees and deadlines with the issuing authority.</small></div><div><h2>Opportunities</h2>{navigation.slice(0, 3).map(([path, label]) => <Link key={path} to={path}>{label}</Link>)}<Link to="/answer-keys">Answer keys</Link><Link to="/syllabus">Syllabus</Link><Link to="/schemes">Government schemes</Link></div><div><h2>Your toolkit</h2><Link to="/tools">All tools</Link><Link to="/tools/image-compressor">Image compressor</Link><Link to="/tools/background-remover">AI background remover</Link><Link to="/tools/image-to-text">Image & PDF to text</Link><Link to="/tools/resume-builder">Résumé builder</Link></div><div><h2>Your workspace</h2><Link to="/account">My dashboard</Link><Link to="/account/login">Sign in / create account</Link><Link to="/search">Search all updates</Link><Link to="/login">Staff sign in</Link><p>We do not collect government application fees.</p></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} SarkariLinks</span><span>Made for your next chapter.</span></div></footer>;
}
