import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import Icon from '../../components/Icon';
import type { PortalTool } from '../tools/Tools';
import { toolCatalog } from '../tools/catalog';

export default function LaunchHero({ tools }: { tools: PortalTool[] }) {
  const [search, setSearch] = useState(''), navigate = useNavigate();
  const matches = tools.filter(tool => toolCatalog[tool.slug] && `${tool.name} ${toolCatalog[tool.slug].category}`.toLowerCase().includes(search.toLowerCase())).slice(0, 4);
  return <><section className="launch-hero"><div className="launch-copy"><span className="launch-kicker"><span /> YOUR EVERYDAY ADVANTAGE</span><h1>Big next steps.<br /><span>Less busywork.</span></h1><p>Discover opportunities. Prepare your documents.<br className="desktop-break" /> Get application-ready with useful tools and local AI.</p><div className="launch-actions"><Link className="button" to="/tools">Find your next tool <span aria-hidden="true">↗</span></Link><Link className="button secondary" to="/jobs">Explore opportunities</Link></div><div className="launch-assurances"><span>✓ Free browser tools</span><span>✓ No account needed to start</span></div></div><section className="launch-desk" aria-labelledby="desk-title"><div className="desk-top"><span className="desk-mark">S<span>+</span></span><div><h2 id="desk-title">What’s on your to-do list?</h2><p>A small tool for your next big step.</p></div><span className="desk-status" aria-label="Browser tools" /></div><label className="desk-search"><Icon name="search" /><span className="sr-only">Find a tool</span><input type="search" value={search} onChange={event => setSearch(event.target.value)} placeholder="Try image, résumé or text…" /></label><div className="desk-tools">{matches.map(tool => <Link key={tool.slug} to={`/tools/${tool.slug}`}><span className="desk-tool-icon"><Icon name={toolCatalog[tool.slug].category === 'Images' ? 'image' : toolCatalog[tool.slug].category === 'Calculators' ? 'calculator' : 'results'} /></span><span><strong>{tool.name}</strong><small>{toolCatalog[tool.slug].category} · {tool.slug === 'media-downloader' ? 'Account required' : 'On your device'}</small></span><span aria-hidden="true">↗</span></Link>)}{matches.length === 0 && <p className="desk-empty">{tools.length ? 'No matching tools. Try another keyword.' : 'Explore the toolkit to see available tools.'}</p>}</div><Link className="desk-all" to="/tools">Explore the complete toolkit <span aria-hidden="true">→</span></Link></section></section><div className="launch-context"><span>ONE PLACE. YOUR NEXT CHAPTER.</span><nav aria-label="Quick access">{[['/jobs', 'Latest jobs'], ['/results', 'Results'], ['/admit-cards', 'Admit cards'], ['/admissions', 'Admissions'], ['/tools', 'Tools & AI']].map(([path, label]) => <Link key={path} to={path}>{label} <span aria-hidden="true">↗</span></Link>)}</nav></div><form className="launch-opportunity-search" role="search" onSubmit={event => { event.preventDefault(); navigate(`/search?q=${encodeURIComponent(String(new FormData(event.currentTarget).get('q') ?? '').trim())}`); }}><Icon name="search" /><label className="sr-only" htmlFor="home-search">Search jobs and updates</label><input id="home-search" name="q" maxLength={150} placeholder="Looking for an exam, job or organization?" /><button className="secondary">Search opportunities →</button></form></>;
}
