import { Link } from 'react-router-dom';
import { Faq } from '../../components/Feedback';
import { ToolCard, type PortalTool } from '../tools/Tools';

export default function ProductSections({ tools }: { tools: PortalTool[] }) {
  return <div className="product-sections">
    <section><div className="section-title"><div><span className="eyebrow">YOUR APPLICATION TOOLKIT</span><h2>From first draft to ready to send.</h2><p>Practical utilities and local AI, together in one place.</p></div><Link to="/tools">Explore tools →</Link></div><div className="tool-grid">{tools.filter(tool => ['background-remover', 'image-to-text', 'resume-builder'].includes(tool.slug)).map(tool => <ToolCard key={tool.slug} tool={tool} />)}</div></section>
    <section className="product-steps"><div><span className="eyebrow">A SIMPLER WORKFLOW</span><h2>Less preparation.<br />More possibility.</h2></div>{[['01', 'Choose your next step', 'Find an opportunity or open the tool your task needs.'], ['02', 'Make it yours', 'Prepare a photo, extract document text or shape your résumé. Review every result.'], ['03', 'Move forward', 'Download your files, save your shortlist and apply through the official source.']].map(([number, title, text]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</section>
    <section className="product-benefits"><div><span className="eyebrow">BUILT FOR REAL TASKS</span><h2>Your work stays in your hands.</h2><p>For job seekers preparing an application, students digitizing notes, and professionals refreshing their résumé.</p></div><div><h3>Local processing, clear boundaries</h3><p>Image tools and OCR run on your device. Saving résumé fields and preparing media downloads use your account and our server.</p><h3>AI where it actually helps</h3><p>Portrait background removal uses a local model. OCR recognizes document text. Converters and calculators are ordinary utilities, clearly labeled.</p><h3>Start without a subscription</h3><p>Use browser tools and export your résumé as a guest. Create a free account for saved jobs, preferences and résumé storage. Paid plans are not currently offered.</p></div></section>
    <Faq items={[{ question: 'Do I need an account to use the tools?', answer: 'Browser image tools, OCR, calculators and résumé export work without signing in. An account is required to save résumé fields, bookmark jobs or prepare supported media downloads.' }, { question: 'Are my documents uploaded?', answer: 'Image processing and OCR happen in your browser. If you choose Save to my account in the résumé builder, the form fields are stored privately on the server. The original imported document stays on your device.' }, { question: 'Is every tool powered by AI?', answer: 'No. Background removal uses a portrait segmentation model and text extraction uses OCR. Format conversion, compression, calculators and résumé formatting do not generate AI content.' }, { question: 'Is SarkariLinks a government service?', answer: 'SarkariLinks is an independent information portal. Check eligibility, deadlines and application instructions with the official issuing authority linked on each notice.' }]} />
    <section className="product-cta"><div><span className="eyebrow">YOUR NEXT STEP, SIMPLIFIED</span><h2>Make room for what comes next.</h2><p>Start with a useful tool. Build a workspace when you need one.</p></div><div className="action-row"><Link className="button" to="/tools">Explore free tools →</Link><Link className="button secondary" to="/account/login">Create your workspace</Link></div></section>
  </div>;
}
