import { useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { staffApi, type StaffUser } from '../../api/session';
import { categories } from '../../api/content';
import { TermFields } from './WorkspacePanels';

export const detailLabels: Record<string, string> = { vacancies: 'Vacancies', eligibility: 'Eligibility & age', fees: 'Application fees', important_dates: 'Important dates', application_process: 'How to apply', benefits: 'Benefits', exam_details: 'Examination details' };
interface ImportItem {
  id: number; filename: string; status: string; source_url: string; content_id: number | null;
  extracted_text: string; error: string | null; created_at: string;
  suggestions: { type: string | null; title: string; summary: string; organization: string; locale: string; closing_date: string | null; details: Record<string, string> } | null;
  extraction: { pages: number; ocr_pages: number; warnings: string[] } | null;
}
export default function Advertisements({ user }: { user: StaffUser }) {
  const client = useQueryClient();
  const [selected, setSelected] = useState<number | null>(null);
  const [page, setPage] = useState(1);
  const [message, setMessage] = useState('');
  const history = useQuery({ queryKey: ['advertisements', page], queryFn: () => staffApi<{ data: ImportItem[]; current_page: number; last_page: number }>(`/admin/advertisements?page=${page}`), refetchInterval: query => query.state.data?.data.some(row => ['queued', 'processing'].includes(row.status)) ? 3000 : false });
  const detail = useQuery({ queryKey: ['advertisement', selected], queryFn: () => staffApi<{ data: ImportItem }>(`/admin/advertisements/${selected}`), enabled: selected !== null, refetchInterval: query => ['queued', 'processing'].includes(query.state.data?.data.status ?? '') ? 2000 : false });
  const upload = useMutation({ mutationFn: (body: FormData) => staffApi<{ data: ImportItem }>('/admin/advertisements', 'POST', body), onSuccess: result => { setSelected(result.data.id); setMessage('File saved. Extraction runs in the background; you can return to this history at any time.'); void client.invalidateQueries({ queryKey: ['advertisements'] }); } });
  const retry = useMutation({ mutationFn: (id: number) => staffApi(`/admin/advertisements/${id}/retry`, 'POST'), onSuccess: () => { void client.invalidateQueries(); } });
  return <section className="panel admin-panel"><div className="import-heading"><div><span className="eyebrow">FROM OFFICIAL NOTICE TO ORGANIZED UPDATE</span><h2>Import an advertisement</h2><p>Upload a PDF or image. Review the extracted text, then save it in the right section.</p></div><span className="role-badge">English + Hindi OCR</span></div><ol className="import-steps"><li><b>1</b> Upload source</li><li><b>2</b> Review extraction</li><li><b>3</b> Create draft</li><li><b>4</b> Editorial approval</li></ol>
    {user.permissions.includes('media.upload') && <form className="upload-zone" onSubmit={event => { event.preventDefault(); upload.mutate(new FormData(event.currentTarget)); }}><label className="upload-file">Advertisement file<input name="file" type="file" accept=".pdf,.png,.jpg,.jpeg" required onChange={event => { event.currentTarget.setCustomValidity((event.currentTarget.files?.[0]?.size ?? 0) > 10485760 ? 'Choose a file smaller than 10 MB.' : ''); }} /><small>PDF, JPG or PNG · Up to 10 MB · PDF: 50 pages · Image: 20 megapixels</small></label><label>Official source URL<input name="source_url" type="url" required maxLength={2048} placeholder="https://department.gov.in/notice" /><small>Use the issuing authority’s notice page for verification.</small></label><button disabled={upload.isPending}>{upload.isPending ? 'Uploading…' : 'Upload & extract'}</button></form>}
    {(upload.error || retry.error) && <p className="admin-error" role="alert">{upload.error?.message ?? retry.error?.message}</p>}{message && <p className="admin-success" role="status">{message}</p>}
    <div className="import-workspace"><aside className="import-history"><h3>Import history</h3>{history.isPending && <p role="status">Loading imports…</p>}{history.error && <p role="alert">{history.error.message}</p>}{history.data?.data.length === 0 && <p>Your uploaded advertisements will appear here.</p>}{history.data?.data.map(item => <button key={item.id} className={`import-history-item ${selected === item.id ? 'active' : ''}`} onClick={() => { setSelected(item.id); setMessage(''); }}><strong>{item.filename}</strong><span className={`status-badge status-${item.status}`}>{item.status}</span><small>{new Date(item.created_at).toLocaleDateString('en-IN')}</small></button>)}{history.data && history.data.last_page > 1 && <div className="row-actions"><button className="secondary" disabled={page <= 1} onClick={() => setPage(page - 1)}>Previous</button><button className="secondary" disabled={page >= history.data.last_page} onClick={() => setPage(page + 1)}>Next</button></div>}</aside><div className="import-review">{!selected && <div className="import-empty"><span aria-hidden="true">↥</span><h3>Start with the official advertisement</h3><p>Extracted text and field suggestions will appear here. Every field stays editable before it becomes a draft.</p></div>}{detail.isFetching && !detail.data && <p role="status">Loading extraction…</p>}{detail.error && <p className="admin-error" role="alert">{detail.error.message}</p>}{detail.data && <><div className="admin-toolbar"><h3>{detail.data.data.filename}</h3><a href={`/api/v1/admin/advertisements/${selected}/download`}>Download original</a></div>{['queued', 'processing'].includes(detail.data.data.status) && <div className="extraction-progress" role="status"><span className="loading-line" /><h3>{detail.data.data.status === 'queued' ? 'Waiting for extraction' : 'Reading your advertisement…'}</h3><p>Large or scanned PDFs can take a few minutes. This page updates automatically.</p></div>}{detail.data.data.status === 'failed' && <div role="alert"><p className="admin-error">{detail.data.data.error}</p><button disabled={retry.isPending} onClick={() => retry.mutate(selected!)}>Retry extraction</button></div>}{detail.data.data.status === 'imported' && <p className="admin-success">Draft #{detail.data.data.content_id} was saved. Open the Content tab to continue the review workflow.</p>}{detail.data.data.status === 'ready' && <ImportReview key={detail.data.data.id} item={detail.data.data} user={user} saved={() => { setMessage('Draft created in the selected section. Submit it from the Content tab for independent review.'); void client.invalidateQueries(); }} />}</>}</div></div>
  </section>;
}

function ImportReview({ item, user, saved }: { item: ImportItem; user: StaffUser; saved: () => void }) {
  const fields = item.suggestions!;
  const allowed = categories.filter(([type]) => user.permissions.includes(`${type}.create`));
  const suggested = allowed.some(([type]) => type === fields.type) ? fields.type! : '';
  const [type, setType] = useState(suggested);
  const [locale, setLocale] = useState(fields.locale);
  const mutation = useMutation({ mutationFn: (body: unknown) => staffApi(`/admin/advertisements/${item.id}/draft`, 'POST', body), onSuccess: saved });
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const details = Object.fromEntries(Object.keys(detailLabels).map(key => [key, data.get(`details.${key}`) || '']));
    const values = Object.fromEntries([...data].filter(([key]) => !key.startsWith('details.') && key !== 'confirmed' && key !== 'term_ids'));
    mutation.mutate({ ...values, term_ids: data.getAll('term_ids').map(Number), closing_date: values.closing_date || null, details });
  }
  return <><p className="import-notice">Suggestions are unverified. Compare dates, fees and eligibility with the original before saving.</p>{item.extraction?.warnings.map((warning, index) => <p className="import-notice" key={index}>{warning}</p>)}<details className="source-text"><summary>Extracted source text · {item.extraction?.pages} pages · {item.extraction?.ocr_pages} OCR pages</summary><pre>{item.extracted_text}</pre></details><form onSubmit={submit} className="content-editor import-form"><fieldset disabled={mutation.isPending || allowed.length === 0}><div className="form-grid"><label>Destination section<select name="type" required value={type} onChange={e => setType(e.target.value)}><option value="">Choose the correct section</option>{allowed.map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label><label>Language<select name="locale" value={locale} onChange={e => setLocale(e.target.value)}><option value="en">English</option><option value="hi">Hindi</option></select></label><label>Title<input name="title" required maxLength={255} defaultValue={fields.title} /></label><label>URL slug<input name="slug" required pattern="[a-z0-9]+(-[a-z0-9]+)*" maxLength={180} defaultValue={`${fields.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 130).replace(/-$/, '') || 'advertisement'}-${item.id}`} /></label><label>Issuing organization<input name="organization" required maxLength={255} defaultValue={fields.organization} /></label><label>Official source URL<input name="source_url" type="url" required maxLength={2048} defaultValue={item.source_url} /></label><label>Closing date (India)<input name="closing_date" type="date" defaultValue={fields.closing_date ?? ''} /></label></div><label>Summary<textarea name="summary" required maxLength={2000} defaultValue={fields.summary} rows={3} /></label><div className="form-grid">{Object.entries(detailLabels).map(([key, label]) => <label key={key}>{label}<textarea name={`details.${key}`} defaultValue={fields.details[key]} maxLength={key === 'vacancies' ? 2000 : key === 'fees' ? 5000 : 10000} rows={3} /></label>)}</div><TermFields key={locale} locale={locale} /><label>Notice details<textarea name="body" required maxLength={100000} defaultValue={item.extracted_text} rows={10} /></label><label className="confirm-extraction"><input name="confirmed" type="checkbox" required />I compared these fields with the source and selected the correct section.</label><button disabled={mutation.isPending}>{mutation.isPending ? 'Creating draft…' : 'Create draft in selected section'}</button></fieldset>{allowed.length === 0 && <p>You do not have permission to create content. An authorized author must create the draft.</p>}{mutation.error && <p className="admin-error" role="alert">{mutation.error.message}</p>}</form></>;
}
