import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { staffApi } from '../../api/session';
import { informationLinks, type InformationPage } from '../pages/SitePages';

interface Settings { version: number; document: { owner: string; support_email: string; address: string; pages: Record<string, InformationPage> }; }
export default function SiteInformation() {
  const [selected, setSelected] = useState('about-us');
  const client = useQueryClient();
  const query = useQuery({ queryKey: ['admin-site-information'], queryFn: () => staffApi<{ data: Settings }>('/admin/site-information'), staleTime: Infinity });
  const save = useMutation({ mutationFn: (body: Settings) => staffApi<{ data: Settings }>('/admin/site-information', 'PUT', body), onSuccess: data => { client.setQueryData(['admin-site-information'], data); void client.invalidateQueries({ queryKey: ['site-page'] }); } });
  return <section className="panel admin-panel"><div className="section-title"><div><h2>Site information</h2><p>Update the public business details and page text. Changes apply to everyone and are audited.</p></div><button className="secondary" onClick={() => { save.reset(); void query.refetch(); }}>Reload saved settings</button></div>{query.isPending && <p role="status">Loading settings…</p>}{query.error && <p role="alert">{query.error.message}</p>}{query.data && <Editor key={query.data.data.version} current={query.data.data} selected={selected} setSelected={setSelected} save={body => save.mutate(body)} pending={save.isPending} />}{save.error && <p role="alert" className="admin-error">{save.error.message}</p>}{save.isSuccess && <p role="status" className="admin-success">Site information saved and audited.</p>}</section>;
}
function Editor({ current, save, pending, selected, setSelected }: { current: Settings; save: (body: Settings) => void; pending: boolean; selected: string; setSelected: (slug: string) => void }) {
  const [document, setDocument] = useState(current.document);
  const page = document.pages[selected];
  function updatePage(value: Partial<InformationPage>) { setDocument({ ...document, pages: { ...document.pages, [selected]: { ...page, ...value } } }); }
  return <form className="site-information-editor" onSubmit={event => { event.preventDefault(); save({ version: current.version, document }); }}><fieldset disabled={pending}><legend>Public business details</legend><div className="form-grid"><label>Site operator / business name<input value={document.owner} maxLength={180} onChange={event => setDocument({ ...document, owner: event.target.value })} /></label><label>Public support email<input type="email" value={document.support_email} maxLength={254} onChange={event => setDocument({ ...document, support_email: event.target.value })} /></label></div><label>Public address (optional)<textarea value={document.address} maxLength={1000} onChange={event => setDocument({ ...document, address: event.target.value })} /></label><p>Use real public details. No sample business identity or email is shown to visitors.</p><label>Page to edit<select value={selected} onChange={event => setSelected(event.target.value)}>{informationLinks.map(([slug, label]) => <option key={slug} value={slug}>{label}</option>)}</select></label><Link to={`/${selected}`} target="_blank" rel="noopener noreferrer">Open published page ↗</Link><label>Page title<input required maxLength={120} value={page.title} onChange={event => updatePage({ title: event.target.value })} /></label><label>Search description<textarea required maxLength={250} value={page.description} onChange={event => updatePage({ description: event.target.value })} /></label>{page.sections.map((section, index) => <div className="information-section-editor" key={`${selected}-${index}`}><label>Section {index + 1} heading<input required maxLength={180} value={section.heading} onChange={event => updatePage({ sections: page.sections.map((item, i) => i === index ? { ...item, heading: event.target.value } : item) })} /></label><label>Section {index + 1} text<textarea required rows={5} maxLength={10000} value={section.text} onChange={event => updatePage({ sections: page.sections.map((item, i) => i === index ? { ...item, text: event.target.value } : item) })} /></label><button className="secondary" type="button" onClick={() => updatePage({ sections: page.sections.filter((_, i) => i !== index) })}>Remove section {index + 1}</button></div>)}<button className="secondary" type="button" disabled={page.sections.length >= 20} onClick={() => updatePage({ sections: [...page.sections, { heading: '', text: '' }] })}>Add section</button><label className="review-policy"><input type="checkbox" checked={page.review_required ?? false} onChange={event => updatePage({ review_required: event.target.checked })} />Mark as draft awaiting operator review</label><p>Review policies against your actual operations before removing the draft label. Draft pages are excluded from the XML sitemap and marked noindex. Text is displayed as plain text, not executable HTML.</p></fieldset><button disabled={pending}>{pending ? 'Saving…' : 'Save site information'}</button></form>;
}
