import ChoiceSwitch from '../../components/ChoiceSwitch';
import { useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { staffApi, type StaffUser } from '../../api/session';
import { getJson, type Content, type Page } from '../../api/content';
import type { Term } from '../admin/WorkspacePanels';

export function useMemberSession() { return useQuery({ queryKey: ['session'], queryFn: () => staffApi<{ data: StaffUser | null }>('/session'), retry: false, staleTime: 30_000 }); }
interface Profile { id: number; name: string; email: string; preferences: Record<string, string>; bookmark_ids: number[]; }
export function MemberAuth() {
  const [register, setRegister] = useState(false);
  const navigate = useNavigate(), client = useQueryClient();
  const session = useMemberSession();
  const [params] = useSearchParams();
  const requestedReturn = params.get('returnTo') ?? '';
  const destination = requestedReturn === '/tools/media-downloader' || /^\/jobs\/[a-zA-Z0-9_-]+(?:\?locale=(?:en|hi))?$/.test(requestedReturn) ? requestedReturn : '/account';
  const mutation = useMutation({ mutationFn: (body: Record<string, unknown>) => staffApi(register ? '/register' : '/session', 'POST', body), onSuccess: async () => { await client.invalidateQueries(); navigate(destination); } });
  if (session.data?.data) return <section className="member-auth panel"><h1>You’re signed in</h1><p>Welcome back, {session.data.data.name}.</p><Link className="button" to="/account">Open my dashboard</Link></section>;
  return <div className="auth-layout"><div className="auth-story"><span className="saas-badge">YOUR NEXT CHAPTER</span><h1>A little more clarity.<br /><em>A lot more possibility.</em></h1><p>Keep your job search, application tools and résumé together in one personal workspace.</p><ul><li>Save the opportunities that matter</li><li>Discover jobs matching your preferences</li><li>Create and save a polished résumé</li></ul><Link to="/jobs">Explore jobs without an account →</Link></div><section className="member-auth panel"><div className="auth-switch"><button className={!register ? 'selected' : ''} onClick={() => { setRegister(false); mutation.reset(); }}>Sign in</button><button className={register ? 'selected' : ''} onClick={() => { setRegister(true); mutation.reset(); }}>Create account</button></div><h2>{register ? 'Start your next chapter' : 'Welcome back'}</h2><p>{register ? 'Your free workspace is a few details away.' : 'Sign in to your jobs, tools and saved résumé.'}</p><form onSubmit={event => { event.preventDefault(); const body = Object.fromEntries(new FormData(event.currentTarget)); mutation.mutate({ ...body, email: String(body.email).trim().toLowerCase() }); }} key={String(register)}>{register && <label>Full name<input name="name" autoComplete="name" required maxLength={100} /></label>}<label>Email address<input name="email" type="email" autoComplete="username" required /></label><label>Password<input name="password" type="password" autoComplete={register ? 'new-password' : 'current-password'} required minLength={register ? 12 : undefined} /></label>{register && <><small>Use 12+ characters with upper/lowercase letters and numbers.</small><label>Confirm password<input name="password_confirmation" type="password" autoComplete="new-password" required /></label></>}{mutation.error && <p className="admin-error" role="alert">{mutation.error.message}</p>}<button disabled={mutation.isPending}>{mutation.isPending ? 'Please wait…' : register ? 'Create my account' : 'Sign in to my workspace'}</button></form><p className="auth-footnote">For content teams: <Link to="/login">Staff sign in</Link></p></section></div>;
}

export function BookmarkButton({ content }: { content: Content }) {
  const session = useMemberSession(), client = useQueryClient();
  const profile = useQuery({ queryKey: ['member-profile'], queryFn: () => staffApi<{ data: Profile }>('/account/profile'), enabled: !!session.data?.data });
  const saved = profile.data?.data.bookmark_ids.includes(content.id);
  const mutation = useMutation({ mutationFn: () => staffApi(`/account/bookmarks/${content.id}`, saved ? 'DELETE' : 'PUT'), onSuccess: async () => { await Promise.all([client.invalidateQueries({ queryKey: ['member-profile'] }), client.invalidateQueries({ queryKey: ['bookmarks'] })]); } });
  const icon = <svg width="16" height="16" viewBox="0 0 24 24" fill={saved ? 'currentColor' : 'none'} stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d="M6 4h12v17l-6-4-6 4V4Z" /></svg>;
  if (session.isPending) return <button className="save-job" type="button" disabled>{icon}Loading...</button>;
  if (!session.data?.data && !session.error) return <Link className="save-job" to={`/account/login?returnTo=${encodeURIComponent(`/jobs/${content.slug}?locale=${content.locale}`)}`}>{icon}Save job</Link>;
  return <span className="bookmark-control"><button type="button" className={`save-job ${saved ? 'is-saved' : ''}`} aria-pressed={!!saved} aria-busy={mutation.isPending} disabled={mutation.isPending || !profile.data} onClick={() => mutation.mutate()}>{icon}{mutation.isPending ? 'Updating...' : saved ? 'Saved' : 'Save job'}</button>{(profile.error || session.error) && <span className="bookmark-error" role="alert">Unable to check saved jobs. <button type="button" className="text-button" onClick={() => void (session.error ? session.refetch() : profile.refetch())}>Retry</button></span>}{mutation.error && <span className="bookmark-error" role="alert">Could not update saved jobs. Please try again.</span>}</span>;
}

export default function Account() {
  const session = useMemberSession(), client = useQueryClient(), navigate = useNavigate();
  const [params, setParams] = useSearchParams();
  const tab = ['saved', 'preferences'].includes(params.get('tab') ?? '') ? params.get('tab')! : 'for-you';
  const setTab = (value: string) => setParams({ tab: value });
  const profile = useQuery({ queryKey: ['member-profile'], queryFn: () => staffApi<{ data: Profile }>('/account/profile'), enabled: !!session.data?.data });
  const logout = useMutation({ mutationFn: () => staffApi('/session', 'DELETE'), onSuccess: () => { client.clear(); navigate('/account/login'); } });
  if (session.isPending) return <p role="status">Opening your workspace…</p>;
  if (session.error) return <p className="admin-error" role="alert">{session.error.message}</p>;
  if (!session.data?.data) return <MemberAuth />;
  return <div className="workspace-frame"><aside className="workspace-sidebar"><span className="eyebrow">WORKSPACE</span><nav aria-label="Workspace navigation"><Link to="/account" aria-current={tab === 'for-you' ? 'page' : undefined}>Overview</Link><Link to="/account?tab=saved" aria-current={tab === 'saved' ? 'page' : undefined}>Saved opportunities</Link><Link to="/tools">Tools &amp; AI</Link><Link to="/tools/resume-builder">My résumé</Link><Link to="/tools/media-downloader">Media history</Link><Link to="/account?tab=preferences" aria-current={tab === 'preferences' ? 'page' : undefined}>Account settings</Link></nav><div className="workspace-plan"><strong>Free workspace</strong><p>Browser tools and résumé export are available without a paid plan.</p><Link to="/tools">Find your next tool →</Link></div></aside><section className="member-dashboard workspace-body"><div className="dashboard-welcome"><div><span className="eyebrow">YOUR PERSONAL WORKSPACE</span><h1>Hello, {session.data.data.name.split(' ')[0]} <span aria-hidden="true">✦</span></h1><p>Your next opportunity starts with one small step.</p></div><button className="secondary" disabled={logout.isPending} onClick={() => logout.mutate()}>{logout.isPending ? 'Signing out…' : 'Sign out'}</button></div>{logout.error && <p role="alert">{logout.error.message}</p>}<div className="dashboard-actions"><Link to="/tools/resume-builder"><b>Build your résumé</b><span>Turn your experience into a great first impression →</span></Link><Link to="/tools"><b>Get application-ready</b><span>Compress a photo, extract text or convert a document →</span></Link></div><nav className="member-tabs" aria-label="My workspace">{[['for-you', 'Jobs for you'], ['saved', 'Saved jobs'], ['preferences', 'Profile & preferences']].map(([key, label]) => <button key={key} className={tab === key ? 'selected' : ''} onClick={() => setTab(key)}>{label}</button>)}</nav>{profile.error && <p role="alert">{profile.error.message}</p>}{tab !== 'preferences' ? <MemberJobs key={tab} saved={tab === 'saved'} /> : profile.data && <Preferences profile={profile.data.data} />}</section></div>;
}

function MemberJobs({ saved }: { saved: boolean }) {
  const [page, setPage] = useState(1);
  const query = useQuery({ queryKey: [saved ? 'bookmarks' : 'recommendations', page], queryFn: () => staffApi<Page>(`/account/${saved ? 'bookmarks' : 'recommendations'}?page=${page}`) });
  return <section><div className="section-title"><div><h2>{saved ? 'Your shortlist' : 'Opportunities for you'}</h2><p>{saved ? 'Keep the notices you want to come back to.' : 'Matches use your state, qualification and department preferences. Without preferences, you’ll see the latest jobs.'}</p></div><Link to="/jobs">Browse all jobs →</Link></div>{query.isPending && <p role="status">Loading jobs…</p>}{query.error && <p role="alert">{query.error.message}</p>}<div className="member-job-grid">{query.data?.data.map(item => <article className="panel member-job" key={item.id}><div className="job-card-top"><span className="eyebrow">{item.organization}</span><BookmarkButton content={item} /></div><Link className="item-title" to={`/${item.type}/${item.slug}?locale=${item.locale}`}>{item.title}</Link><p>{item.summary}</p><small>{item.closing_date ? `Apply by ${item.closing_date}` : `Published ${new Date(item.published_at).toLocaleDateString('en-IN')}`}</small></article>)}</div>{query.data?.data.length === 0 && <div className="empty-workspace"><span>♡</span><h3>{saved ? 'Your shortlist starts here' : 'No matches just yet'}</h3><p>{saved ? 'Save a job from its notice page to find it here.' : 'Try broader preferences or browse all published jobs.'}</p><Link className="button" to="/jobs">Explore latest jobs</Link></div>}{query.data && query.data.meta.last_page > 1 && <div className="pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page} of {query.data.meta.last_page}</span><button disabled={page >= query.data.meta.last_page} onClick={() => setPage(page + 1)}>Next</button></div>}</section>;
}

function Preferences({ profile }: { profile: Profile }) {
  const [locale, setLocale] = useState(profile.preferences.locale ?? 'en');
  const terms = useQuery({ queryKey: ['terms', locale], queryFn: () => getJson<{ data: Term[] }>(`/terms?locale=${locale}`) });
  const client = useQueryClient();
  const mutation = useMutation({ mutationFn: (body: unknown) => staffApi('/account/profile', 'PUT', body), onSuccess: () => { void client.invalidateQueries({ queryKey: ['member-profile'] }); void client.invalidateQueries({ queryKey: ['recommendations'] }); } });
  const password = useMutation({ mutationFn: (body: unknown) => staffApi('/account/password', 'PUT', body) });
  function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); mutation.mutate({ name: data.get('name'), preferences: { locale, ...Object.fromEntries(['state', 'qualification', 'department'].map(key => [key, data.get(key) || null])) } }); }
  return <div className="profile-grid"><form className="panel settings-form" onSubmit={save}><h2>Make it personal</h2><label>Your name<input name="name" required defaultValue={profile.name} maxLength={100} /></label><label>Email<input type="email" value={profile.email} disabled /></label><ChoiceSwitch label="Preferred language" value={locale} onChange={value => setLocale(value)} options={[["en", "English"], ["hi", "Hindi"]]} /><div key={`${locale}-${terms.data?.data.length ?? 0}`}>{['state', 'qualification', 'department'].map(group => <label key={group}>{group}<select name={group} defaultValue={profile.preferences.locale === locale ? profile.preferences[group] ?? '' : ''}><option value="">Any {group}</option>{terms.data?.data.filter(term => term.taxonomy === group).map(term => <option key={term.id} value={term.slug}>{term.label}</option>)}</select></label>)}</div>{terms.error && <p role="alert">{terms.error.message}</p>}{mutation.error && <p role="alert">{mutation.error.message}</p>}{mutation.isSuccess && <p className="admin-success" role="status">Preferences saved. Your job suggestions are updated.</p>}<button disabled={mutation.isPending}>Save preferences</button></form><form className="panel settings-form" onSubmit={event => { event.preventDefault(); const form = event.currentTarget; password.mutate(Object.fromEntries(new FormData(form)), { onSuccess: () => form.reset() }); }}><h2>Account security</h2><label>Current password<input type="password" name="current_password" autoComplete="current-password" required /></label><label>New password<input type="password" name="password" autoComplete="new-password" minLength={12} required /></label><label>Confirm new password<input type="password" name="password_confirmation" autoComplete="new-password" required /></label><small>Use 12+ characters with upper/lowercase letters and numbers.</small>{password.error && <p role="alert">{password.error.message}</p>}{password.isSuccess && <p role="status">Password updated.</p>}<button disabled={password.isPending}>Update password</button></form></div>;
}
