export const toolCatalog: Record<string, { icon: string; category: string; description: string; steps: string[] }> = {
  'pdf-compressor': { icon: 'P', category: 'Documents', description: 'Optimize PDFs or reduce scanned document size locally. Compare actual file sizes before downloading.', steps: ['Choose a plain PDF up to 10 MB and 50 pages.', 'Select optimization or image-only scanned compression.', 'Compare sizes, preview the first page and download.'] },
  'pdf-merge-split': { icon: 'P', category: 'Documents', description: 'Combine PDFs in your chosen order or extract selected pages into a new PDF. Files stay on your device.', steps: ['Choose Merge PDFs or Extract pages.', 'Add and reorder files, or specify page ranges such as 1, 3-5.', 'Preview and download the resulting PDF.'] },
  'image-converter': { icon: '▧', category: 'Images', description: 'Convert JPG, PNG and WebP images directly in your browser. Resize photos for forms, websites and everyday sharing.', steps: ['Choose an image.', 'Select the format, quality and width.', 'Preview and download your converted file.'] },
  'image-compressor': { icon: '↘', category: 'Images', description: 'Reduce photo file size with adjustable quality and dimensions. See the actual output size before downloading.', steps: ['Choose a JPG, PNG or WebP photo.', 'Select JPG or WebP and adjust quality or width.', 'Compare file sizes and download the result.'] },
  'background-remover': { icon: '✦', category: 'AI & OCR', description: 'Remove portrait backgrounds with local AI and download a transparent PNG. Best for clear photographs of people.', steps: ['Choose a portrait with a clearly visible person.', 'Let the local model create a transparent background.', 'Review the edges and download your PNG.'] },
  'image-to-text': { icon: 'T', category: 'AI & OCR', description: 'Extract English and Hindi text from photos, scanned documents and PDFs with local OCR. Review and edit the result before using it.', steps: ['Choose an image or a PDF of up to 10 pages.', 'Extract text using local English and Hindi OCR.', 'Review the text and download a TXT file.'] },
  'resume-builder': { icon: '▤', category: 'Career', description: 'Build a résumé with modern, classic or minimal templates. Import an existing document using OCR, preview changes and export a PDF.', steps: ['Enter your details or import a PDF or photo.', 'Review your experience and choose a template.', 'Print to PDF or save the fields to your private account.'] },
  'media-downloader': { icon: '↓', category: 'Media', description: 'Prepare permitted public videos or MP3 audio from supported YouTube, Instagram and Facebook links. Sign-in required.', steps: ['Paste a public link to media you own or may download.', 'Choose video or MP3 and prepare your download.', 'Download the result within one hour. Platform restrictions may prevent processing.'] },
  'image-to-pdf': { icon: 'P', category: 'Documents', description: 'Place a photo or scanned page into a clean A4 PDF. Convert locally without uploading your document.', steps: ['Choose your image.', 'Create a PDF with the image fitted onto A4.', 'Download your document.'] },
  age: { icon: '◷', category: 'Career', description: 'Calculate completed age on a specific eligibility cut-off date. Always check the official notice for age relaxation rules.', steps: ['Enter your date of birth.', 'Set the cut-off date from the official notice.', 'Calculate completed years.'] },
  percentage: { icon: '%', category: 'Calculators', description: 'Calculate your marks percentage from marks obtained and maximum marks.', steps: ['Enter marks obtained.', 'Enter the maximum possible marks.', 'Calculate your percentage.'] },
  emi: { icon: '₹', category: 'Calculators', description: 'Estimate equal monthly payments from a loan amount, fixed annual rate and repayment period. Fees and lender-specific charges are excluded.', steps: ['Enter the principal and annual interest rate.', 'Choose the number of monthly payments.', 'Calculate an indicative monthly payment.'] },
};
