import { useMutation, useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { staffApi } from '../../api/session';
import { useMemberSession } from '../account/Account';
import { size } from './browser-tools';
interface Download { id: string; title: string | null; url: string; format: string; status: string; size: number | null; error: string | null; expires_at: string; }
export default function MediaDownloader() {
  const session = useMemberSession();
  const query = useQuery({ queryKey: ['media-downloads'], queryFn: () => staffApi<{ data: Download[] }>('/account/downloads'), enabled: !!session.data?.data, refetchInterval: q => q.state.data?.data.some(item => ['queued', 'processing'].includes(item.status)) ? 3000 : false });
  const mutation = useMutation({ mutationFn: (body: unknown) => staffApi('/account/downloads', 'POST', body), onSuccess: () => { void query.refetch(); } });
  return <div className="tool-workspace"><section className="panel tool-controls"><h2>One link. Your media.</h2><p>Download your own or permitted public videos from YouTube, Instagram and Facebook. Choose video or MP3 audio.</p><p>Up to 10 minutes and 50 MB. Availability depends on the platform; private, login-only, live and protected media are unsupported.</p>{session.data?.data ? <form onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); mutation.mutate({ url: data.get('url'), format: data.get('format'), permission: data.get('permission') === 'on' }); }}><label>Public media URL<input name="url" type="url" required placeholder="https://www.youtube.com/watch?v=..." maxLength={2048} /></label><label>Download format<select name="format"><option value="video">Video · up to 720p</option><option value="audio">Audio / music · MP3</option></select></label><label className="checkbox-label"><input type="checkbox" name="permission" required />I own this media or have permission to download it.</label><button disabled={mutation.isPending}>Prepare download</button>{mutation.error && <p role="alert">{mutation.error.message}</p>}</form> : <Link className="button" to="/account/login">Sign in to prepare a download</Link>}<small>This tool processes the public link on our server. Downloads are private to your account and expire after one hour.</small></section><section className="panel tool-output"><h2>Your downloads</h2>{query.isPending && session.data?.data && <p role="status">Loading downloads...</p>}{query.error && <p role="alert">{query.error.message}</p>}{!query.data?.data.length && <div className="tool-empty"><span aria-hidden="true">↓</span><p>Your prepared files will appear here.</p></div>}{query.data?.data.map(item => <article className="download-item" key={item.id}><h3>{item.title || 'Media download'}</h3><p className="file-name">{item.url}</p><p role="status">{item.status === 'ready' ? `Ready · ${size(item.size ?? 0)}` : item.status === 'failed' ? 'Could not prepare this download' : `${item.status === 'queued' ? 'Queued' : 'Processing'} · This may take a few minutes`}</p>{item.error && <p>{item.error}</p>}{item.status === 'ready' && <a className="button" href={`/api/v1/account/downloads/${item.id}/file`}>Download {item.format === 'audio' ? 'MP3' : 'video'}</a>}</article>)}</section></div>;
}
