import { lazy, Suspense, useState, useEffect } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link, useParams } from 'react-router-dom';
import { getJson } from '../../api/content';
import { toolCatalog } from './catalog';
import Calculator from './Calculator';
import { rememberTool } from '../home/ReturnVisit';
const ImageTools = lazy(() => import('./ImageTools'));
const ResumeBuilder = lazy(() => import('./ResumeBuilder'));
const MediaDownloader = lazy(() => import('./MediaDownloader'));
export interface PortalTool { slug: string; name: string; help: string; enabled?: boolean; }
export function ToolCard({ tool }: { tool: PortalTool }) { const info = toolCatalog[tool.slug]; if (!info) return null; return <Link className="tool-card" to={`/tools/${tool.slug}`}><div className="tool-card-top"><span aria-hidden="true" className={`tool-icon tone-${info.category.split(' ')[0].toLowerCase()}`}>{info.icon}</span><span className="tool-category">{info.category}</span></div><h3>{tool.name}</h3><p>{info.description}</p><span className="tool-open">Open tool <span aria-hidden="true">↗</span></span></Link>; }
export default function Tools() {
  const { tool: slug } = useParams();
  const [search, setSearch] = useState(''), [category, setCategory] = useState('All tools');
  const query = useQuery({ queryKey: ['tools'], queryFn: () => getJson<{ data: PortalTool[] }>('/tools') });
  useEffect(() => { if (slug && query.data?.data.some(tool => tool.slug === slug)) rememberTool(slug); }, [slug, query.data]);
  if (query.isPending) return <p role="status">Loading tools...</p>;
  if (query.error) return <p role="alert">{query.error.message}</p>;
  const available = query.data?.data.filter(tool => toolCatalog[tool.slug]) ?? [];
  const tool = available.find(item => item.slug === slug), info = slug ? toolCatalog[slug] : null;
  if (slug) return tool && info ? <section className="tool-detail"><Link className="back-link" to="/tools">← All tools</Link><div className="tool-detail-heading"><span className="tool-icon">{info.icon}</span><div><span className="eyebrow">{info.category} · {slug === 'media-downloader' ? 'ACCOUNT REQUIRED' : 'PROCESSED ON YOUR DEVICE'}</span><h1>{tool.name}</h1><p>{info.description}</p></div></div><Suspense fallback={<p role="status">Opening your tool...</p>}>{['age', 'percentage', 'emi'].includes(slug) ? <Calculator tool={tool} /> : slug === 'resume-builder' ? <ResumeBuilder /> : slug === 'media-downloader' ? <MediaDownloader /> : <ImageTools slug={slug} key={slug} />}</Suspense><section className="tool-how"><h2>How to use {tool.name.toLowerCase()}</h2><ol>{info.steps.map(step => <li key={step}>{step}</li>)}</ol><p>{tool.help}</p></section><div className="section-title"><h2>Keep things moving</h2><Link to="/tools">Explore all tools →</Link></div><div className="tool-grid related-tools">{available.filter(item => item.slug !== slug).slice(0, 3).map(item => <ToolCard key={item.slug} tool={item} />)}</div></section> : <section><h1>Tool unavailable</h1><p>This tool is not currently enabled.</p><Link to="/tools">Browse available tools</Link></section>;
  const filtered = available.filter(tool => (category === 'All tools' || toolCatalog[tool.slug].category === category) && `${tool.name} ${toolCatalog[tool.slug].description}`.toLowerCase().includes(search.toLowerCase()));
  return <section className="tools-directory"><div className="tools-hero"><span className="saas-badge">LESS BUSYWORK. MORE POSSIBILITY.</span><h1>Small tools.<br /><em>Big everyday wins.</em></h1><p>Make your next application, document or creative task a little easier. Useful tools, with local AI where it helps.</p><label className="tool-search"><span className="sr-only">Find a tool</span><input type="search" placeholder="Find a tool... try image, résumé or PDF" value={search} onChange={e => setSearch(e.target.value)} /></label><div className="privacy-pills"><span>✓ Image files stay on your device</span><span>✓ No AI subscription needed</span></div></div><div className="tool-tabs" aria-label="Tool categories">{['All tools', ...new Set(available.map(tool => toolCatalog[tool.slug].category))].map(group => <button key={group} className={category === group ? 'selected' : ''} aria-pressed={category === group} onClick={() => setCategory(group)}>{group}</button>)}</div><p className="tool-count" role="status">{filtered.length} tools to make room for what matters</p><div className="tool-grid">{filtered.map(tool => <ToolCard key={tool.slug} tool={tool} />)}</div>{filtered.length === 0 && <div className="empty-workspace"><h2>No tools found</h2><p>Try another search or category.</p><button onClick={() => { setSearch(''); setCategory('All tools'); }}>Show all tools</button></div>}<div className="tools-bottom"><span className="tool-icon">✦</span><div><h2>Your files. Your control.</h2><p>Image editing, OCR and résumé previews run in your browser. Account saves and media-link downloads are clearly marked when server processing is needed.</p></div></div></section>;
}
